### ISSUE TITLE
Exit code 0 on failure

### ISSUE THREAD

**Issue by jakob-tsd** [marcinbor85/can-prog#2]
Thanks again for can-prog! I am scripting around can-prog right now and noticed that it exits with code zero even if the operation has failed:

```
# canprog -i socketcan -n can0 stm32 write fw.dump ; echo $?
[10:13:40.770] main INFO: Connecting target
[10:13:41.770] main ERROR: Connecting error: Receiving timeout
0
```
I'd suggest exiting with code 1 if the operation fails.

**Comment by marcinbor85** [comment]
exit code 0 only if successfull
